stages:
  - test

Test:
  image: node:latest
  stage: test
  tags:
    - linux
    - mysql

  variables:
    MYSQL_ROOT_PASSWORD: "secret"

  cache:
    paths:
      - node_modules/

  script:
    - mysql --version
